repos:
- repo: https://github.com/espressif/astyle_py.git
  rev: v1.0.5
  hooks:
  - id: astyle_py
    args: ['--astyle-version=3.4.7', '--rules=tools/ci/astyle-rules.yml']

- repo: https://github.com/google/keep-sorted
  rev: v0.7.1
  hooks:
  - id: keep-sorted

- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
  - id: codespell
    args: ['--config=.codespellrc', '--write-changes']
